export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST'
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS'
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL'
export const ADMIN_SIGNOUT  = 'ADMIN_SIGNOUT'

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL'

export const ADMIN_GET_CARDS_REQUEST = 'ADMIN_GET_CARDS_REQUEST'
export const ADMIN_GET_CARDS_SUCCESS = 'ADMIN_GET_CARDS_SUCCESS'
export const ADMIN_GET_CARDS_FAIL = 'ADMIN_GET_CARDS_FAIL'

export const ADMIN_GET_USERS_REQUEST = 'ADMIN_GET_USERS_REQUEST'
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS'
export const ADMIN_GET_USERS_FAIL = 'ADMIN_GET_USERS_FAIL'