export const USER_GET_CARDS_REQUEST = 'USER_GET_CARDS_REQUEST'
export const USER_GET_CARDS_SUCCESS = 'USER_GET_CARDS_SUCCESS'
export const USER_GET_CARDS_FAIL = 'USER_GET_CARDS_FAIL'
export const USER_ADD_CARD_REQUEST = "USER_ADD_CARD_REQUEST"
export const USER_ADD_CARD_SUCCESS = "USER_ADD_CARD_SUCCESS"
export const USER_ADD_CARD_FAIL = "USER_ADD_CARD_FAIL"
export const USER_GET_MY_CARDS_REQUEST = 'USER_GET_MY_CARDS_REQUEST'
export const USER_GET_MY_CARDS_SUCCESS = 'USER_GET_MY_CARDS_SUCCESS'
export const USER_GET_MY_CARDS_FAIL = 'USER_GET_MY_CARDS_FAIL'

export const USER_GENERATE_CARD_REQUEST = "USER_GENERATE_CARD_REQUEST"
export const USER_GENERATE_CARD_SUCCESS = "USER_GENERATE_CARD_SUCCESS"
export const USER_GENERATE_CARD_FAIL = "USER_GENERATE_CARD_FAIL"